name: Reusable LAUNCH TEST

on:
  workflow_dispatch:

jobs:
    launch-workflow-run-npm-test:
      uses: MaximeDehayDealinka/test-ci/.github/workflows/ex4.yml@main 
      with:
        node-version: 20
      